# Generated by Django 5.2.3 on 2025-11-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
